# default
server:
  address: localhost
  port: 8080

spring:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql:  true
        format_sql: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace


--- # sbl
spring:
  config:
    activate:
      on-profile: "db-sbl"


  datasource:
    url: jdbc:mysql://localhost:3306/schema1?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&userSSL=true
    username: springboot
    password: 0801
    driver-class-name: com.mysql.cj.jdbc.Driver



--- # dell
spring:
  config:
    activate:
      on-profile: "db-dell"


  datasource:
      url: jdbc:mysql://localhost:3306/jisoo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&userSSL=true
      username: root
      password: 0801
      driver-class-name: com.mysql.cj.jdbc.Driver

